spring:
  application:
    name: spring-cloud-gateway-app

  cloud:
    gateway:
      routes:
        - id: helloservice-route
          uri: lb://HELLOSERVICE
          predicates:
            - Path=/rest/service/**
          filters:
            - name: CircuitBreaker
              args:
                name: helloServiceCircuitBreaker
                fallbackUri: forward:/myfallback
            
server:
  port: 8072

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health